version: '3'

services:
  backend:
    build: ./backend
    container_name: codien_backend
    ports:
      - "8080:8080"
    networks:
      - codien_net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/codien
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456

  frontend:
    build: ./frontend
    container_name: codien_frontend
    ports:
      - "80:80"
    networks:
      - codien_net
    depends_on:
      - backend

  mysql:
    image: mysql:8
    container_name: codien_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: codien
    ports:
      - "3306:3306"
    volumes:
      - ./db/codien_dump.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - codien_net

networks:
  codien_net:
    driver: bridge
